### ISSUE TITLE
problem with script

### ISSUE THREAD

**Issue by crxpirate** [bberthelemy/apc-mini-lights-controller#1]
Hi man
thanks in advance for ure precious work
anyway, i'm not good in python i only try to use ure example json

pythons, mido and rtmidi are installed.

after i run 
keymap.midi.py keymap.example.json

i got this

Traceback (most recent call last):
  File "C:\k\mido\keymap.midi.py", line 59, in <module>
    msg = create_msg(km)
  File "C:\k\mido\keymap.midi.py", line 45, in create_msg
    if km.has_key("enabled") and km["enabled"] == False:
AttributeError: 'dict' object has no attribute 'has_key'

where's the problem? thank u man! i want only the light stay on / off .. no matter blinkin or color, just to remind what button are pressed or or not.

THANK U MAN !!

**Comment by bberthelemy** [comment]
Hello bro, i'm glad you find it useful. I added python 3 compatibility because the script was written for python2 initially.

It should work now, if you have the same issue, try to use python 2.

**Comment by ingenieur-du-grenier** [comment]
Hello @crxpirate , i'm glad you find it useful. I added python 3 compatibility because the script was written for python2 initially.

It should work now, if you have the same issue, try to use python 2.

**Comment by crxpirate** [comment]
hi man. thank u! now no more error but lights still not working!
i use the example json... nothing!
if i try edit script with TRUE on blinking, nothing change
i try enable every single key.. nothing

i remove other midi keyboard and use midi ox to sniff number (BTW, i've 01 02 03 numbers on my key.. and also 3A 3B... as key...but i cannot put it into scripts, goes error!)

is there somthin i can send u for test?
u got a json can work better?

thank u man !

**Comment by ingenieur-du-grenier** [comment]
@crxpirate 

ok i found out, i'm not using windows so i missed some parts, windows has already a port used for midi stuff so we need to use the name of the port used to send data to it.

I made some changes in the source code, it should work now.
In 3 easy steps ->

**Step 1 - (connect the apc with usb) List ports:**
`python keymap.midi.py -l`

It should print something like this :
```
-> "APC MINI 1"
-> "... another port ..."
```

**Step 2 - Find the one related to APC, in this case it's "APC MINI 1"**
**Step 3 - Then use the -p option to use this port :**
`python keymap.midi.py -p "APC MINI 1" -i keymap.example.json`

**Comment by crxpirate** [comment]
perfect ! now it works. thanks!!!! finally more usefull. Now i dream if there's a way to make it light-unlight when i press a button.. or its only one way command from python?
thank u really much for support !!!

**Comment by ingenieur-du-grenier** [comment]
Well everything is possible, with mido you can get input too. But it requires some coding and to have a permanent script running in background... maybe not the best option.
Maybe you can save some patterns with multiple json files, and then activate / desactive one by one according to your needs.
